version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every month
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    groups:
       # Specify a name for the group, which will be used in PR titles and branch names
       dev-dependencies:
          patterns:
            - "*"  

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every month
      interval: "monthly"
