name: 'tests'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: 'lts/*'

      - name: 'Cache Node dependencies'
        uses: 'actions/cache@v3'
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 'Install dependencies'
        run: 'npm ci'

      - name: 'Run tests'
        run: 'npm test'

      - name: 'Build website'
        if: ${{ github.ref == 'refs/heads/main' }}
        run: 'npm run build --if-present'

      - name: 'Deploy'
        if: |
          github.ref == 'refs/heads/main' && github.event.repository.fork == false
        uses: 'peaceiris/actions-gh-pages@v3'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
