name: 'tests'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v2'
        with:
          node-version: 'lts/*'

      - name: 'Cache Node dependencies'
        uses: 'actions/cache@v2'
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 'Install dependencies'
        run: 'npm ci'

      - name: 'Run build if present'
        run: 'npm run build --if-present'

      - name: 'Run tests'
        run: 'npm test'
